config/routes.rb
Rails.application.routes.draw do
  
  root to: "profiles#index"
  resources :profiles do
    delete 'destroy_image/:id', on: :collection, action: :destroy_image, as: :destroy_image
    resources :documents
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :profile

  mount_uploader :docs, PictureUploader
  validates_integrity_of :docs
  serialize :docs

end

app/models/profile.rb
class Profile < ApplicationRecord

  has_many :documents, dependent: :destroy

  mount_uploaders :picture, PictureUploader
  validates_integrity_of :picture
  serialize :picture

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @document = @profile.documents.new(document_params)

    respond_to do |format|
      if @document.save
        format.json { render json: @document, status: :created }
      else
        format.json { render json: @document.errors }
      end
    end
  end

  def update
    permit_params = params.require(:document).permit(:docs)
    respond_to do |format|
      if @document.update(permit_params)
        format.html { redirect_to profile_path(@profile), notice: 'Document was successfully updated.' }
      else
        format.html { redirect_to profile_path(@profile), notice: 'Document was failed to updated.' }
      end
    end
  end

  def destroy
    image_path = File.join(Rails.root, 'public', @document.docs.to_s)
    File.delete(image_path) if File.exist?(image_path)
    @document.destroy
    redirect_to profile_path(@profile), notice: 'Document was successfully destroyed.' 
  end

  private
    def set_document
      @document = Document.find(params[:id])
      @profile = Profile.find(params[:profile_id])
    end

    def document_params
      params.require(:document).permit(:docs)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile, only: [:show, :edit, :update, :destroy, :destroy_image]

  def index
    @profiles = Profile.all
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_image
    image_path = File.join(Rails.root, 'public', params["data"])
    File.delete(image_path) if File.exist?(image_path)
    pic_array = @profile["picture"]
    image_name = params["data"].split('/').last
    pic_array.delete(image_name) if pic_array.include?(image_name)
    @profile.save
    redirect_to profile_path(@profile), notice: 'Document was successfully destroyed.'
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, {picture: []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/documents/_show.html.erb
<% if documents.present? %>
  <p>
    <strong>Profile:</strong>
    <%= @profile.id %>
  </p>

  <strong>Documents:</strong>
  <% documents&.each do |document| %>
    <p>
      <%= image_tag(document.docs.url, style:"height: 300px; width:500px") %>
      <%= link_to 'Delete', profile_document_path(@profile, document), method: :delete %> 
    </p>
      <%= link_to 'Edit', edit_profile_document_path(@profile, document) %> 
  <% end %>

<% end %>

app/views/documents/edit.html.erb
<%= form_for(@document, url: profile_document_path(@document.profile, @document), method: :put, local: true) do |form| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% @document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "field" >
    <%= form.label :docs %>
    <%= form.file_field :docs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/new.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.2/min/dropzone.min.js"></script>

<%= javascript_pack_tag 'doc_dropzone' %>
<%= form_with(model: document, url: profile_documents_path(document.profile), html: { multipart: true, class: 'dropzone', id: 'myAwesomeDropzone'}) do |form| %>

  <div class= "fallback" >
    <%= form.file_field :docs, multiple: true %>
  </div>
  
  <%= button_to 'Submit', "#", id: 'button', class: 'btn btn-success'  %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carrierwave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class= "field" >
    <%= form.label :picture %>
    <%= form.file_field :picture, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>Create Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<strong>Pictures:</strong>
<% @profile.picture&.each do |picture| %>
  <p>
    <%= image_tag(picture.url, style:"height: 300px; width:500px") %>
    <%= link_to 'Delete', destroy_image_profiles_path(@profile, data: picture), method: :delete %> 
  </p>
<% end %>

<div style="border-style: double;">
  <div class="docs-div">
    <%= render partial: "documents/show", locals: {documents: @profile.documents} %>
  </div>
  
  <div class="new-docs-div">
    <%= render template: "documents/new", locals: {document: @profile.documents.build }  %>
  </div>

</div>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>